CREATE TABLE kota_kabupaten (
    id SERIAL PRIMARY KEY,
    kode_provinsi VARCHAR(10),
    kode_kabkota VARCHAR(10),
    nama_kabkota VARCHAR(100)
);

INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.01', 'KAB. ACEH SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.02', 'KAB. ACEH TENGGARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.03', 'KAB. ACEH TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.04', 'KAB. ACEH TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.05', 'KAB. ACEH BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.06', 'KAB. ACEH BESAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.07', 'KAB. PIDIE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.08', 'KAB. ACEH UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.09', 'KAB. SIMEULUE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.10', 'KAB. ACEH SINGKIL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.11', 'KAB. BIREUEN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.12', 'KAB. ACEH BARAT DAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.13', 'KAB. GAYO LUES');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.14', 'KAB. ACEH JAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.15', 'KAB. NAGAN RAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.16', 'KAB. ACEH TAMIANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.17', 'KAB. BENER MERIAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.18', 'KAB. PIDIE JAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.71', 'KOTA BANDA ACEH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.72', 'KOTA SABANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.73', 'KOTA LHOKSEUMAWE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.74', 'KOTA LANGSA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('11', '11.75', 'KOTA SUBULUSSALAM');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.01', 'KAB. TAPANULI TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.02', 'KAB. TAPANULI UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.03', 'KAB. TAPANULI SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.04', 'KAB. NIAS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.05', 'KAB. LANGKAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.06', 'KAB. KARO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.07', 'KAB. DELI SERDANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.08', 'KAB. SIMALUNGUN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.09', 'KAB. ASAHAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.10', 'KAB. LABUHANBATU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.11', 'KAB. DAIRI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.12', 'KAB. TOBA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.13', 'KAB. MANDAILING NATAL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.14', 'KAB. NIAS SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.15', 'KAB. PAKPAK BHARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.16', 'KAB. HUMBANG HASUNDUTAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.17', 'KAB. SAMOSIR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.18', 'KAB. SERDANG BEDAGAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.19', 'KAB. BATU BARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.20', 'KAB. PADANG LAWAS UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.21', 'KAB. PADANG LAWAS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.22', 'KAB. LABUHANBATU SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.23', 'KAB. LABUHANBATU UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.24', 'KAB. NIAS UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.25', 'KAB. NIAS BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.71', 'KOTA MEDAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.72', 'KOTA PEMATANGSIANTAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.73', 'KOTA SIBOLGA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.74', 'KOTA TANJUNG BALAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.75', 'KOTA BINJAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.76', 'KOTA TEBING TINGGI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.77', 'KOTA PADANG SIDEMPUAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('12', '12.78', 'KOTA GUNUNGSITOLI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.01', 'KAB. PESISIR SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.02', 'KAB. SOLOK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.03', 'KAB. SIJUNJUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.04', 'KAB. TANAH DATAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.05', 'KAB. PADANG PARIAMAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.06', 'KAB. AGAM');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.07', 'KAB. LIMA PULUH KOTA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.08', 'KAB. PASAMAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.09', 'KAB. KEPULAUAN MENTAWAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.10', 'KAB. DHARMASRAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.11', 'KAB. SOLOK SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.12', 'KAB. PASAMAN BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.71', 'KOTA PADANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.72', 'KOTA SOLOK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.73', 'KOTA SAWAHLUNTO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.74', 'KOTA PADANG PANJANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.75', 'KOTA BUKITTINGGI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.76', 'KOTA PAYAKUMBUH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('13', '13.77', 'KOTA PARIAMAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.01', 'KAB. KAMPAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.02', 'KAB. INDRAGIRI HULU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.03', 'KAB. BENGKALIS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.04', 'KAB. INDRAGIRI HILIR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.05', 'KAB.  PELALAWAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.06', 'KAB.  ROKAN HULU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.07', 'KAB.  ROKAN HILIR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.08', 'KAB. SIAK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.09', 'KAB. KUANTAN SINGINGI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.10', 'KAB. KEPULAUAN MERANTI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.71', 'KOTA PEKANBARU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('14', '14.72', 'KOTA DUMAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.01', 'KAB.  KERINCI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.02', 'KAB.  MERANGIN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.03', 'KAB. SAROLANGUN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.04', 'KAB. BATANGHARI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.05', 'KAB.  MUARO JAMBI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.06', 'KAB. TANJUNG JABUNG BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.07', 'KAB. TANJUNG JABUNG TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.08', 'KAB. BUNGO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.09', 'KAB. TEBO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.71', 'KOTA JAMBI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('15', '15.72', 'KOTA SUNGAI PENUH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.01', 'KAB. OGAN KOMERING ULU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.02', 'KAB. OGAN KOMERING ILIR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.03', 'KAB. MUARA ENIM');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.04', 'KAB. LAHAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.05', 'KAB. MUSI RAWAS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.06', 'KAB. MUSI BANYUASIN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.07', 'KAB. BANYUASIN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.08', 'KAB. OGAN KOMERING ULU TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.09', 'KAB. OGAN KOMERING ULU SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.10', 'KAB. OGAN ILIR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.11', 'KAB. EMPAT LAWANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.12', 'KAB. PENUKAL ABAB LEMATANG ILIR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.13', 'KAB. MUSI RAWAS UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.71', 'KOTA PALEMBANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.72', 'KOTA PAGAR ALAM');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.73', 'KOTA LUBUK LINGGAU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('16', '16.74', 'KOTA PRABUMULIH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.01', 'KAB. BENGKULU SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.02', 'KAB. REJANG LEBONG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.03', 'KAB. BENGKULU UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.04', 'KAB. KAUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.05', 'KAB. SELUMA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.06', 'KAB. MUKO MUKO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.07', 'KAB. LEBONG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.08', 'KAB. KEPAHIANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.09', 'KAB. BENGKULU TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('17', '17.71', 'KOTA BENGKULU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.01', 'KAB. LAMPUNG SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.02', 'KAB. LAMPUNG TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.03', 'KAB. LAMPUNG UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.04', 'KAB. LAMPUNG BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.05', 'KAB. TULANG BAWANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.06', 'KAB. TANGGAMUS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.07', 'KAB. LAMPUNG TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.08', 'KAB. WAY KANAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.09', 'KAB. PESAWARAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.10', 'KAB. PRINGSEWU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.11', 'KAB. MESUJI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.12', 'KAB. TULANG BAWANG BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.13', 'KAB. PESISIR BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.71', 'KOTA BANDAR LAMPUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('18', '18.72', 'KOTA METRO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('19', '19.01', 'KAB. BANGKA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('19', '19.02', 'KAB. BELITUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('19', '19.03', 'KAB. BANGKA SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('19', '19.04', 'KAB. BANGKA TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('19', '19.05', 'KAB. BANGKA BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('19', '19.06', 'KAB. BELITUNG TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('19', '19.71', 'KOTA PANGKAL PINANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('21', '21.01', 'KAB. BINTAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('21', '21.02', 'KAB. KARIMUN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('21', '21.03', 'KAB. NATUNA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('21', '21.04', 'KAB. LINGGA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('21', '21.05', 'KAB. KEPULAUAN ANAMBAS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('21', '21.71', 'KOTA BATAM');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('21', '21.72', 'KOTA TANJUNG PINANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('31', '31.01', 'KAB. ADM. KEP. SERIBU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('31', '31.71', 'KOTA ADM. JAKARTA PUSAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('31', '31.72', 'KOTA ADM. JAKARTA UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('31', '31.73', 'KOTA ADM. JAKARTA BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('31', '31.74', 'KOTA ADM. JAKARTA SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('31', '31.75', 'KOTA ADM. JAKARTA TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.01', 'KAB. BOGOR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.02', 'KAB. SUKABUMI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.03', 'KAB. CIANJUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.04', 'KAB. BANDUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.05', 'KAB. GARUT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.06', 'KAB. TASIKMALAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.07', 'KAB. CIAMIS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.08', 'KAB. KUNINGAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.09', 'KAB. CIREBON');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.10', 'KAB. MAJALENGKA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.11', 'KAB. SUMEDANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.12', 'KAB. INDRAMAYU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.13', 'KAB. SUBANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.14', 'KAB. PURWAKARTA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.15', 'KAB. KARAWANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.16', 'KAB. BEKASI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.17', 'KAB. BANDUNG BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.18', 'KAB. PANGANDARAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.71', 'KOTA BOGOR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.72', 'KOTA SUKABUMI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.73', 'KOTA BANDUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.74', 'KOTA CIREBON');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.75', 'KOTA BEKASI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.76', 'KOTA DEPOK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.77', 'KOTA CIMAHI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.78', 'KOTA TASIKMALAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('32', '32.79', 'KOTA BANJAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.01', 'KAB. CILACAP');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.02', 'KAB. BANYUMAS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.03', 'KAB. PURBALINGGA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.04', 'KAB. BANJARNEGARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.05', 'KAB. KEBUMEN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.06', 'KAB. PURWOREJO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.07', 'KAB. WONOSOBO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.08', 'KAB. MAGELANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.09', 'KAB. BOYOLALI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.10', 'KAB. KLATEN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.11', 'KAB. SUKOHARJO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.12', 'KAB. WONOGIRI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.13', 'KAB. KARANGANYAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.14', 'KAB. SRAGEN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.15', 'KAB. GROBOGAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.16', 'KAB. BLORA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.17', 'KAB. REMBANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.18', 'KAB. PATI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.19', 'KAB. KUDUS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.20', 'KAB. JEPARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.21', 'KAB. DEMAK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.22', 'KAB. SEMARANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.23', 'KAB. TEMANGGUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.24', 'KAB. KENDAL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.25', 'KAB. BATANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.26', 'KAB. PEKALONGAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.27', 'KAB. PEMALANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.28', 'KAB. TEGAL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.29', 'KAB. BREBES');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.71', 'KOTA MAGELANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.72', 'KOTA SURAKARTA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.73', 'KOTA SALATIGA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.74', 'KOTA SEMARANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.75', 'KOTA PEKALONGAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('33', '33.76', 'KOTA TEGAL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('34', '34.01', 'KAB. KULON PROGO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('34', '34.02', 'KAB. BANTUL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('34', '34.03', 'KAB. GUNUNGKIDUL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('34', '34.04', 'KAB. SLEMAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('34', '34.71', 'KOTA YOGYAKARTA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.01', 'KAB. PACITAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.02', 'KAB. PONOROGO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.03', 'KAB. TRENGGALEK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.04', 'KAB. TULUNGAGUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.05', 'KAB. BLITAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.06', 'KAB. KEDIRI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.07', 'KAB. MALANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.08', 'KAB. LUMAJANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.09', 'KAB. JEMBER');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.10', 'KAB. BANYUWANGI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.11', 'KAB. BONDOWOSO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.12', 'KAB. SITUBONDO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.13', 'KAB. PROBOLINGGO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.14', 'KAB. PASURUAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.15', 'KAB. SIDOARJO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.16', 'KAB. MOJOKERTO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.17', 'KAB. JOMBANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.18', 'KAB. NGANJUK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.19', 'KAB. MADIUN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.20', 'KAB. MAGETAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.21', 'KAB. NGAWI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.22', 'KAB. BOJONEGORO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.23', 'KAB. TUBAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.24', 'KAB. LAMONGAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.25', 'KAB. GRESIK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.26', 'KAB. BANGKALAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.27', 'KAB. SAMPANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.28', 'KAB. PAMEKASAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.29', 'KAB. SUMENEP');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.71', 'KOTA KEDIRI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.72', 'KOTA BLITAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.73', 'KOTA MALANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.74', 'KOTA PROBOLINGGO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.75', 'KOTA PASURUAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.76', 'KOTA MOJOKERTO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.77', 'KOTA MADIUN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.78', 'KOTA SURABAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('35', '35.79', 'KOTA BATU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('36', '36.01', 'KAB. PANDEGLANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('36', '36.02', 'KAB. LEBAK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('36', '36.03', 'KAB. TANGERANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('36', '36.04', 'KAB. SERANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('36', '36.71', 'KOTA TANGERANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('36', '36.72', 'KOTA CILEGON');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('36', '36.73', 'KOTA SERANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('36', '36.74', 'KOTA TANGERANG SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.01', 'KAB. JEMBRANA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.02', 'KAB. TABANAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.03', 'KAB. BADUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.04', 'KAB. GIANYAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.05', 'KAB. KLUNGKUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.06', 'KAB. BANGLI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.07', 'KAB. KARANGASEM');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.08', 'KAB. BULELENG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('51', '51.71', 'KOTA DENPASAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.01', 'KAB. LOMBOK BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.02', 'KAB. LOMBOK TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.03', 'KAB. LOMBOK TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.04', 'KAB. SUMBAWA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.05', 'KAB. DOMPU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.06', 'KAB. BIMA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.07', 'KAB. SUMBAWA BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.08', 'KAB. LOMBOK UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.71', 'KOTA MATARAM');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('52', '52.72', 'KOTA BIMA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.01', 'KAB. KUPANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.02', 'KAB TIMOR TENGAH SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.03', 'KAB. TIMOR TENGAH UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.04', 'KAB. BELU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.05', 'KAB. ALOR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.06', 'KAB. FLORES TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.07', 'KAB. SIKKA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.08', 'KAB. ENDE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.09', 'KAB. NGADA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.10', 'KAB. MANGGARAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.11', 'KAB. SUMBA TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.12', 'KAB. SUMBA BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.13', 'KAB. LEMBATA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.14', 'KAB. ROTE NDAO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.15', 'KAB. MANGGARAI BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.16', 'KAB. NAGEKEO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.17', 'KAB. SUMBA TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.18', 'KAB. SUMBA BARAT DAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.19', 'KAB. MANGGARAI TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.20', 'KAB. SABU RAIJUA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.21', 'KAB. MALAKA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('53', '53.71', 'KOTA KUPANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.01', 'KAB. SAMBAS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.02', 'KAB. MEMPAWAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.03', 'KAB. SANGGAU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.04', 'KAB. KETAPANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.05', 'KAB. SINTANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.06', 'KAB. KAPUAS HULU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.07', 'KAB. BENGKAYANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.08', 'KAB. LANDAK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.09', 'KAB. SEKADAU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.10', 'KAB. MELAWI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.11', 'KAB. KAYONG UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.12', 'KAB. KUBU RAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.71', 'KOTA PONTIANAK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('61', '61.72', 'KOTA SINGKAWANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.01', 'KAB. KOTAWARINGIN BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.02', 'KAB. KOTAWARINGIN TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.03', 'KAB. KAPUAS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.04', 'KAB. BARITO SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.05', 'KAB. BARITO UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.06', 'KAB. KATINGAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.07', 'KAB. SERUYAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.08', 'KAB. SUKAMARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.09', 'KAB. LAMANDAU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.10', 'KAB. GUNUNG MAS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.11', 'KAB. PULANG PISAU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.12', 'KAB. MURUNG RAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.13', 'KAB. BARITO TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('62', '62.71', 'KOTA PALANGKARAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.01', 'KAB. TANAH LAUT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.02', 'KAB. KOTABARU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.03', 'KAB. BANJAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.04', 'KAB. BARITO KUALA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.05', 'KAB. TAPIN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.06', 'KAB. HULU SUNGAI SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.07', 'KAB. HULU SUNGAI TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.08', 'KAB. HULU SUNGAI UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.09', 'KAB. TABALONG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.10', 'KAB. TANAH BUMBU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.11', 'KAB. BALANGAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.71', 'KOTA BANJARMASIN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('63', '63.72', 'KOTA BANJARBARU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.01', 'KAB. PASER');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.02', 'KAB. KUTAI KARTANEGARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.03', 'KAB. BERAU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.07', 'KAB. KUTAI BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.08', 'KAB. KUTAI TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.09', 'KAB. PENAJAM PASER UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.11', 'KAB. MAHAKAM ULU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.71', 'KOTA BALIKPAPAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.72', 'KOTA SAMARINDA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('64', '64.74', 'KOTA BONTANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('65', '65.01', 'KAB. BULUNGAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('65', '65.02', 'KAB. MALINAU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('65', '65.03', 'KAB. NUNUKAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('65', '65.04', 'KAB. TANA TIDUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('65', '65.71', 'KOTA TARAKAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.01', 'KAB. BOLAANG MONGONDOW');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.02', 'KAB. MINAHASA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.03', 'KAB. KEPULAUAN SANGIHE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.04', 'KAB. KEPULAUAN TALAUD');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.05', 'KAB. MINAHASA SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.06', 'KAB. MINAHASA UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.07', 'KAB. MINAHASA TENGGARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.08', 'KAB. BOLAANG MONGONDOW UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.09', 'KAB. KEP. SIAU TAGULANDANG BIARO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.10', 'KAB. BOLAANG MONGONDOW TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.11', 'KAB. BOLAANG MONGONDOW SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.71', 'KOTA MANADO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.72', 'KOTA BITUNG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.73', 'KOTA TOMOHON');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('71', '71.74', 'KOTA KOTAMOBAGU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.01', 'KAB. BANGGAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.02', 'KAB. POSO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.03', 'KAB. DONGGALA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.04', 'KAB. TOLI TOLI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.05', 'KAB. BUOL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.06', 'KAB. MOROWALI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.07', 'KAB. BANGGAI KEPULAUAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.08', 'KAB. PARIGI MOUTONG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.09', 'KAB. TOJO UNA UNA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.10', 'KAB. SIGI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.11', 'KAB. BANGGAI LAUT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.12', 'KAB. MOROWALI UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('72', '72.71', 'KOTA PALU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.01', 'KAB. KEPULAUAN SELAYAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.02', 'KAB. BULUKUMBA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.03', 'KAB. BANTAENG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.04', 'KAB. JENEPONTO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.05', 'KAB. TAKALAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.06', 'KAB. GOWA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.07', 'KAB. SINJAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.08', 'KAB. BONE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.09', 'KAB. MAROS');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.10', 'KAB. PANGKAJENE DAN KEPULAUAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.11', 'KAB. BARRU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.12', 'KAB. SOPPENG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.13', 'KAB. WAJO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.14', 'KAB. SIDENRENG RAPPANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.15', 'KAB. PINRANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.16', 'KAB. ENREKANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.17', 'KAB. LUWU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.18', 'KAB. TANA TORAJA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.22', 'KAB. LUWU UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.24', 'KAB. LUWU TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.26', 'KAB. TORAJA UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.71', 'KOTA MAKASSAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.72', 'KOTA PAREPARE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('73', '73.73', 'KOTA PALOPO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.01', 'KAB. KOLAKA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.02', 'KAB. KONAWE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.03', 'KAB. MUNA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.04', 'KAB. BUTON');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.05', 'KAB. KONAWE SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.06', 'KAB. BOMBANA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.07', 'KAB. WAKATOBI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.08', 'KAB. KOLAKA UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.09', 'KAB. KONAWE UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.10', 'KAB. BUTON UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.11', 'KAB. KOLAKA TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.12', 'KAB. KONAWE KEPULAUAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.13', 'KAB. MUNA BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.14', 'KAB. BUTON TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.15', 'KAB. BUTON SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.71', 'KOTA KENDARI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('74', '74.72', 'KOTA BAU BAU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('75', '75.01', 'KAB. GORONTALO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('75', '75.02', 'KAB. BOALEMO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('75', '75.03', 'KAB. BONE BOLANGO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('75', '75.04', 'KAB. POHUWATO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('75', '75.05', 'KAB. GORONTALO UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('75', '75.71', 'KOTA GORONTALO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('76', '76.01', 'KAB. PASANGKAYU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('76', '76.02', 'KAB. MAMUJU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('76', '76.03', 'KAB. MAMASA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('76', '76.04', 'KAB. POLEWALI MANDAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('76', '76.05', 'KAB. MAJENE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('76', '76.06', 'KAB. MAMUJU TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.01', 'KAB. MALUKU TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.02', 'KAB. MALUKU TENGGARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.03', 'KAB. KEPULAUAN TANIMBAR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.04', 'KAB. BURU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.05', 'KAB. SERAM BAGIAN TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.06', 'KAB. SERAM BAGIAN BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.07', 'KAB. KEPULAUAN ARU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.08', 'KAB. MALUKU BARAT DAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.09', 'KAB. BURU SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.71', 'KOTA AMBON');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('81', '81.72', 'KOTA TUAL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.01', 'KAB. HALMAHERA BARAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.02', 'KAB. HALMAHERA TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.03', 'KAB. HALMAHERA UTARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.04', 'KAB. HALMAHERA SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.05', 'KAB. KEPULAUAN SULA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.06', 'KAB. HALMAHERA TIMUR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.07', 'KAB. PULAU MOROTAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.08', 'KAB. PULAU TALIABU');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.71', 'KOTA TERNATE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('82', '82.72', 'KOTA TIDORE KEPULAUAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.03', 'KAB. JAYAPURA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.05', 'KAB. KEPULAUAN YAPEN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.06', 'KAB. BIAK NUMFOR');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.10', 'KAB. SARMI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.11', 'KAB. KEEROM');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.15', 'KAB. WAROPEN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.19', 'KAB. SUPIORI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.20', 'KAB. MAMBERAMO RAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('91', '91.71', 'KOTA JAYAPURA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('92', '92.02', 'KAB. MANOKWARI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('92', '92.03', 'KAB. FAK FAK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('92', '92.06', 'KAB. TELUK BINTUNI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('92', '92.07', 'KAB. TELUK WONDAMA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('92', '92.08', 'KAB. KAIMANA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('92', '92.11', 'KAB. MANOKWARI SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('92', '92.12', 'KAB. PEGUNUNGAN ARFAK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('93', '93.01', 'KAB. MERAUKE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('93', '93.02', 'KAB. BOVEN DIGOEL');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('93', '93.03', 'KAB. MAPPI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('93', '93.04', 'KAB. ASMAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('94', '94.01', 'KAB. NABIRE');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('94', '94.02', 'KAB. PUNCAK JAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('94', '94.03', 'KAB. PANIAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('94', '94.04', 'KAB. MIMIKA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('94', '94.05', 'KAB. PUNCAK');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('94', '94.06', 'KAB. DOGIYAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('94', '94.07', 'KAB. INTAN JAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('94', '94.08', 'KAB. DEIYAI');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('95', '95.01', 'KAB. JAYAWIJAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('95', '95.02', 'KAB PEGUNUNGAN BINTANG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('95', '95.03', 'KAB. YAHUKIMO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('95', '95.04', 'KAB. TOLIKARA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('95', '95.05', 'KAB. MAMBERAMO TENGAH');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('95', '95.06', 'KAB. YALIMO');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('95', '95.07', 'KAB. LANNY JAYA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('95', '95.08', 'KAB. NDUGA');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('96', '96.01', 'KAB. SORONG');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('96', '96.02', 'KAB. SORONG SELATAN');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('96', '96.03', 'KAB. RAJA AMPAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('96', '96.04', 'KAB. TAMBRAUW');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('96', '96.05', 'KAB. MAYBRAT');
INSERT INTO kota_kabupaten (kode_provinsi, kode_kabkota, nama_kabkota) VALUES ('96', '96.71', 'KOTA SORONG');